<svelte:head>
	<title>Impressum — NobleCause.ai</title>
	<meta name="robots" content="noindex" />
</svelte:head>

<p class="kicker">Rechtliches</p>
<h1>Impressum</h1>

<h2>Deutsch</h2>
<h2>Verantwortlich für diese Website</h2>
<p>
	Afschin Mirhamed<br />
	Zuercherstrasse 160<br />
	4052 Basel, Schweiz<br />
	Kontakt: <a href="mailto:contact@noblecause.ai">contact@noblecause.ai</a>
</p>

<h2>Hinweis zu AI-generierten Inhalten</h2>
<p>
	Die auf dieser Website veröffentlichten Deliberationen und Empfehlungen werden von AI-Modellen
	erzeugt und ungekürzt dokumentiert. Sie sind keine Finanz-, Anlage- oder Rechtsberatung. AI-Modelle
	können irren; Konfidenzangaben sind Selbsteinschätzungen der Modelle, keine Garantien. Prüfe
	Empfehlungen eigenständig, bevor du ihnen folgst.
</p>

<h2>Kein Geldfluss</h2>
<p>
	NobleCause.ai nimmt keine Spenden an, sammelt kein Geld und wickelt keine Zahlungen ab. Links auf
	Spendenwege führen ausschließlich zu den offiziellen Seiten der jeweiligen Organisationen; für
	deren Inhalte sind diese Organisationen verantwortlich.
</p>

<h2>Datenschutz</h2>
<p>
	Diese Website ist statisch. Sie verwendet keine Cookies, kein Tracking, keine Analyse-Dienste und
	keine eingebetteten Inhalte von Drittservern. Beim Abruf fallen technisch bedingte Server-Logs
	(IP-Adresse, Zeitpunkt, abgerufene Ressource) an, die zur Betriebssicherheit kurzfristig
	gespeichert und nicht mit anderen Daten zusammengeführt werden.
</p>

<h2>Lizenzen</h2>
<p>
	Inhalte und Protokolle stehen unter
	<a href="https://creativecommons.org/licenses/by/4.0/deed.de">CC BY 4.0</a>, der Quellcode unter
	MIT-Lizenz im
	<a href="https://github.com/noblecause-ai/NobleCause.ai">öffentlichen Repository</a>.
</p>

<h2>English</h2>

<h2>Responsible For This Website</h2>
<p>
	Afschin Mirhamed<br />
	Zuercherstrasse 160<br />
	4052 Basel, Switzerland<br />
	Contact: <a href="mailto:contact@noblecause.ai">contact@noblecause.ai</a>
</p>

<h2>Notice On AI-Generated Content</h2>
<p>
	The deliberations and recommendations published on this website are generated by AI models and
	documented in full. They are not financial, investment, or legal advice. AI models can be wrong;
	confidence values are model self-assessments, not guarantees. Verify recommendations independently
	before acting on them.
</p>

<h2>No Money Flows</h2>
<p>
	NobleCause.ai does not accept donations, collect money, or process payments. Donation links point
	only to official pages of the respective organizations; those organizations are responsible for
	their own content.
</p>

<h2>Data Protection</h2>
<p>
	This website is static. It uses no cookies, no tracking, no analytics services, and no embedded
	content from third-party servers. Technical server logs (IP address, timestamp, requested
	resource) may be stored briefly for operational security and are not merged with other data.
</p>

<h2>Licenses</h2>
<p>
	Content and protocols are published under
	<a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC BY 4.0</a>, source code under the
	MIT license in the
	<a href="https://github.com/noblecause-ai/NobleCause.ai">public repository</a>.
</p>
